kind: pipeline
name: prod-system

steps:
- name: build
  image: node:latest
  commands:
    - node -v
    - npm -v
    - yarn --version
    - yarn install
    - yarn build
    - echo ${DRONE_TAG}
    - echo "{\"version}"
