kind: pipeline
name: default
when:
  ref:
  - refs/tags/*
  branch:
  - dev

steps:
- name: build
  image: node:latest
  commands:
    - node -v
    - npm -v
    - yarn --version
    - yarn install
    - yarn buildDev
