kind: pipeline
name: default

steps:
- name: build
  image: node:latest
  commands:
    - node -v
    - npm -v
    - yarn --version
    - yarn install
    - yarn buildDev
    - echo ${DRONE_COMMIT_SHA}
    - echo ${DRONE_TAG}

