kind: pipeline
name: default

trigger:
  branch:
    - master
    - dev
  event:
    - push
    - tag

steps:
- name: build
  image: node:latest
  commands:
    - node -v
    - npm -v
    - yarn --version
    - yarn install
    - yarn buildDev
    - echo ${DRONE_COMMIT_SHA}
    - echo ${DRONE_TAG}
  when:
    event:
      - push
    branch:
      - dev
